services:
  llm:
    build:
      context: .
      dockerfile: Dockerfile.llama.cpu
    container_name: llama-cpu
    ports:
      - "127.0.0.1:${LLAMA_PORT:-8001}:8001"
    volumes:
      - ./models:/models
    environment:
      - LLAMA_CACHE=/models
    command:
      - "-hf"
      - "${CPU_HF_MODEL:-unsloth/gemma-4-12b-it-GGUF:UD-Q4_K_XL}"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8001"
      - "-c"
      - "${LLAMA_CTX_SIZE:-16384}"
      - "--temp" # Based on unsloth recommendation for mtp models https://unsloth.ai/docs/models/mtp
      - "0.6"
      - "--top-p"
      - "0.95"
      - "--top-k"
      - "20"
      - "--min-p"
      - "0.00"
      - "--alias"
      - "${CPU_HF_MODEL_ALIAS:-unsloth/gemma-4-12b-it-GGUF}"
      - "--threads"
      - "12" # Considering AMD Ryzen Zen 5. Making four threads available for 9950xd.
      - "--spec-type"
      - "draft-mtp"
      - "--spec-draft-n-max"
      - "2"
    restart: unless-stopped

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    profiles:
      - interactive
    volumes:
      - ./workspace:/workspace
      - ./agent_data:/home/node/.pi
    depends_on:
      - llm
